language: python
python:
  - "2.7"

install: 
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install -r requerimientos2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_retry pip install -r requerimientos3.txt; fi

before_script: 
  - autopep8 -ir *
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry flake8 --max-complexity=8 --exclude=*.txt,*.md,*.pyc *; fi

script: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_retry echo python3; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry echo python2; fi

  - python TestCalculadora.py
  - coverage run --branch TestCalculadora.py
  - coverage report -m

notifications:
  email: false