language: python
python:
  - "2.7"
  - "3.4"

install: 
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install -r requerimientos2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_retry pip install -r requerimientos3.txt; fi

before_script: 
  - autopep8 -ir *
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry flake8 --max-complexity=8 --exclude=*.txt,*.md,*.pyc *; fi

script: 
  - chmod +x script.sh
  - ./script.sh

notifications:
  email: false